### ISSUE TITLE
Investigation: Performance regression on Phoenix.

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/phoenix-next#1002]
### Current Behavior

I noticed that our page load time has been creeping up the past few weeks & threatening to undo all the performance work we did a while back! In particular, it looks like our average load time skyrocketed on June 14th at 11:04am.

![what happened](https://user-images.githubusercontent.com/583202/42172200-578b9b9e-7de9-11e8-9de8-721132903289.png)

That roughly corresponds to [this 10:45am production deploy](https://dosomething.slack.com/archives/C3ASB4204/p1528987528000152) ([diff](https://github.com/DoSomething/phoenix-next/compare/94def57a...d92352b0)), which we rolled-back and then [re-deployed at 3:47pm](https://dosomething.slack.com/archives/C2BPA7M8F/p1529005600000286) ([diff](https://github.com/DoSomething/phoenix-next/compare/d92352b0...d2b8fbc6)) with some hotfixes. We also launched the [Brake It Down quiz](https://www.dosomething.org/us/campaigns/brake-it-down/quiz/best-friend) that day... which, oh -- includes an [inexplicably huge 26.4MB image](https://downloads.ctfassets.net/81iqaqpfd8fy/2WLOicYW2AiaAS4iy0IKWk/ce071ef5e87f5f7f73350eddb55f1b6a/Driving.jpg?w=300). Yikes!!

### Expected Behavior
Page load time should be hovering in the 3-4s range.

#### Additional Information
N/A

### Relevant Screenshots + Links
N/A

**Comment by DFurnes** [comment]
> We also launched the [Brake It Down quiz](https://www.dosomething.org/us/campaigns/brake-it-down/quiz/best-friend) that day... which, oh -- includes an [inexplicably huge 26.4MB image](https://downloads.ctfassets.net/81iqaqpfd8fy/2WLOicYW2AiaAS4iy0IKWk/ce071ef5e87f5f7f73350eddb55f1b6a/Driving.jpg?w=300). Yikes!!

I swapped that image (which linked from `https://downloads.ctfassets.net`) to use the Images API by uploading a [new image](https://app.contentful.com/spaces/81iqaqpfd8fy/assets/4xpT2rK61aUA0QAOocmasu) on Contentful's Media tab & using that `https://images.ctfassets.net` URL instead (which supports the `?w=300` query string). That quiz is now 1.4MB total, way better.

**Comment by DFurnes** [comment]
In the future, let's see if we can just throw (and display an empty/broken image fallback) if we get a non-resizable URL there, since this is an easy mistake for an editor to make. We should also look into how we can automatically size down images in Markdown, like the big ol' 1.6MB Adam Garner on the [pitch page](https://www.dosomething.org/us/campaigns/red-white-booth) for this campaign).

**Comment by DFurnes** [comment]
cc: @ashleybaldwin @weerd for tickets!

**Comment by DFurnes** [comment]
Also added a `?w=400` to that picture of Adam in the Markdown source as a quick fix.

**Comment by ashleybaldwin** [comment]
https://www.pivotaltracker.com/n/projects/2019313/stories/158769476 an issue for tracking!

**Comment by mendelB** [comment]
I bumped into another huge image in markdown (from a Contentful asset and not a non-resizable URL). 

It occurred to me that we _do_ have a [Markdown image resizer](https://github.com/DoSomething/phoenix-next/blob/master/resources/assets/components/utilities/Markdown/Markdown.js#L13) but for some reason, this wasn't being applied. 

It seems that Contentful [switched their asset domains](https://www.contentful.com/blog/2017/12/08/change-of-the-contentful-asset-domain/) from `images.contentful.com → images.ctfassets.net` so our override no longer finds the image in [pattern matching](https://github.com/DoSomething/phoenix-next/blob/master/resources/assets/components/utilities/Markdown/Markdown.js#L11)!

**Comment by DFurnes** [comment]
Closing, since this has been investigated & should be fixed up! 🎩 ↕️ @mendelB!
