### ISSUE TITLE
CMD+Click triggers main tab link

### ISSUE THREAD

**Issue by lkpttn** [DoSomething/phoenix-next#1031]
### Current Behavior
When command+clicking on an embedded link, it will open the link both in a new tab and the current tab.

### Expected Behavior
When command-clicking, the link should only open in the new tab and the main page should remain the same.

### Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Go to: https://www.dosomething.org/us/campaigns/the-talk/action
2. Command click on an embedded link

## Context
Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Mac OS X High Sierra
* Browser Version: Firefox latest

**Comment by DFurnes** [comment]
Closing this since we have a Pivotal ticket for it! [#159087483](https://www.pivotaltracker.com/story/show/159087483)
