### ISSUE TITLE
Investigation: Lots of H27s on Sincerely Us.

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/phoenix-next#1048]
### Current Behavior

I noticed that we have a lot of [H27 (request interrupted) errors](https://devcenter.heroku.com/articles/error-codes#h27-client-request-interrupted) happening on [Sincerely Us](https://www.dosomething.org/us/campaigns/sincerely-us), consistently happening each day even though the campaign has been closed for a long while. From [our logs](https://papertrailapp.com/systems/dosomething-phoenix/events?q=H27&focus=959282414029537299):

```
Jul 26 16:39:55 dosomething-phoenix heroku/router:  sock=client at=warning code=H27 desc="Client Request Interrupted" method=GET path="/us/campaigns/sincerely-us" host=next.dosomething.org request_id=b3e1f2e8-5876-4957-8c84-48c8376a13cc fwd="18.217.159.174,23.235.46.26" dyno=web.1 connect=0ms service=48ms status=499 bytes= protocol=https 
Jul 26 16:41:55 dosomething-phoenix heroku/router:  sock=client at=warning code=H27 desc="Client Request Interrupted" method=GET path="/us/campaigns/sincerely-us" host=next.dosomething.org request_id=a7169c30-4699-4d59-9341-83b39b5845b6 fwd="34.201.89.115,23.235.46.26" dyno=web.1 connect=1ms service=46ms status=499 bytes= protocol=https
...
```

### Expected Behavior

Ideally, we don't have weird behavior like this! I don't think this is an issue on our end since it's a client request interrupt, but it does seem awfully weird that it keeps happening so consistently.

#### Additional Information
Pivotal ID: [#]()

**Comment by DFurnes** [comment]
It does seem like all these requests are coming from [one source](https://papertrailapp.com/groups/8135982/events?q=18.217.159.174%2C23.235.46.26&focus=960157433534255109)... maybe a web crawler?

**Comment by DFurnes** [comment]
Swapped that to hit `/us/campaigns/grab-mic` instead, but I think this is safe to close.

The more you know! 💫

**Comment by weerd** [comment]
Woah, haha! Nice find @DFurnes 👍

**Comment by DFurnes** [comment]
One last follow-up on this: I added a simple [response validation](https://docs.newrelic.com/docs/synthetics/new-relic-synthetics/using-monitors/add-edit-monitors#settings) to this monitor ("is 'DoSomething.org' on the page?") and it seems that instructed NR to [load the full page](https://user-images.githubusercontent.com/583202/43408991-a51759b2-93f0-11e8-9d85-31c69dcaf368.png) and silenced those H27s.

**Comment by DFurnes** [comment]
I also removed the EU servers from the synthetics location pool since some of the "green" test results were coming from [sorry.dosomething.org](https://sorry.dosomething.org), which doesn't really tell us much!
