### ISSUE TITLE
React components are borked

### ISSUE THREAD

**Issue by weerd** [DoSomething/phoenix-next#107]
![screen shot 2017-03-29 at 9 32 12 am](https://cloud.githubusercontent.com/assets/105849/24460496/7818c4b4-146c-11e7-8b77-da3292ccb95c.png)

Something is up w/ the components on the staging site.

**Comment by deadlybutter** [comment]
It almost looks like the React components never got compiled to HTML....

**Comment by weerd** [comment]
The single letter component names like `<M>` is definitely due to the minification, but more concerning are the `<Unknown/>` elements.

**Comment by DFurnes** [comment]
This seems to be [a known issue](https://git.io/vSsiM) when components are the default export in a module.
