### ISSUE TITLE
Contentful Query Taking 4Ever!

### ISSUE THREAD

**Issue by mendelB** [DoSomething/phoenix-next#1222]
### Current Behavior

What is the current behavior?
Something we've noticed about our Phoenix queries to Contentful (via the Contentful client and QueriesContentful trait in Laraval) is that it was taking an unusually long time for some pretty simple index queries.

@weerd raised this point specifically regarding the [CampaignController#index](https://github.com/DoSomething/phoenix-next/blob/master/app/Http/Controllers/CampaignController.php#L33) related query, specifically the [GetAllCampaignsPaginated query](https://github.com/DoSomething/phoenix-next/blob/master/app/Repositories/CampaignRepository.php#L58) which although the index is limiting the call to 36 entries, would still lag for a very long time, prompting [varnish cache timeouts via Fastly](https://www.pivotaltracker.com/story/show/162718264).

This could be nailed down more specifically to the [QueriesContentful#GetEntriesAsJson](https://github.com/DoSomething/phoenix-next/blob/master/app/Repositories/QueriesContentful.php#L22) method.

### Expected Behavior

Describe the behavior you are expecting.

We'd reasonably expect this query to be reasonably quick especially since it's being paginated in the campaigns index example. But we see it take -sometimes- a good 20-30 seconds to complete.

#### Additional Information

_Any other info or references to cards/tickets from other services (Trello, etc)._
Pivotal ID: [#162718264](https://www.pivotaltracker.com/story/show/162718264)

**Comment by mendelB** [comment]
After throwing some `Carbon::now`s across the `getEntriesAsJson` method, things *seem* to indicate that the culprit is the JSONification of the entries. 

Altering the method with the following dumps:
```php
protected function getEntriesAsJson($type, $limit = null, $skip = null)
    {
        $query = (new Query)
                ->setContentType($type)
                ->setInclude(0)
                ->orderBy('sys.updatedAt', true)
                ->setLimit($limit)
                ->setSkip($skip);

        dump('Querying Contentful! ', Carbon::now());
        $entries = app('contentful.delivery')->getEntries($query)->getItems();
        dump('Querying Contentful Done! ', Carbon::now());

        switch ($type) {
            case 'campaign':
                // Using the TruncatedCampaign Entity to avoid returning a monstrous object.
                dump('Constructing Entries! ', Carbon::now());
                $results = collect($entries)->mapInto(TruncatedCampaign::class);
                dump('Constructing Entries Done! ', Carbon::now());

                dump('Transforming to JSON! ', Carbon::now());
                $json = $results->toJson();
                dd('Transforming to JSON Done! ', Carbon::now());

            case 'homePage':
                $results = collect($entries)->mapInto(HomePage::class);

                return $results->toJson();
        }
    }
```

yields:
```txt
"Querying Contentful! "
Carbon @1547064519 {#420 ▼
  date: 2019-01-09 20:08:39.581853 UTC (+00:00)
}
"Querying Contentful Done! "
Carbon @1547064520 {#437 ▼
  date: 2019-01-09 20:08:40.143888 UTC (+00:00)
}
"Constructing Entries! "
Carbon @1547064520 {#437 ▼
  date: 2019-01-09 20:08:40.144493 UTC (+00:00)
}
"Constructing Entries Done! "
Carbon @1547064520 {#437 ▼
  date: 2019-01-09 20:08:40.150613 UTC (+00:00)
}
"Transforming to JSON! "
Carbon @1547064520 {#437 ▼
  date: 2019-01-09 20:08:40.151075 UTC (+00:00)
}
"Transforming to JSON Done! "
Carbon @1547064527 {#1690 ▼
  date: 2019-01-09 20:08:47.279923 UTC (+00:00)
}
```

Which shows the JSON transformation being is a whopping 7 seconds long while the query lasts a single second. (This is a generous example, as we've seen 15+ second long lag time.)

Interestingly, examining the `TruncatedCampaign` objects seems to show them containing *all* campaign fields - which is understandable given that we only limit the fields in the [`jsonSerialize`](https://github.com/DoSomething/phoenix-next/blob/e42812dd73aabfa1a27d20dc3c0a20c343afae48/app/Entities/TruncatedCampaign.php#L14) function. 
But what is puzzling is why that then takes so long to JSON serialize, if we are limiting to just a few simple fields, would take so long.

**Comment by mendelB** [comment]
Hmm, we do seem to have two fields within [`TruncatedCampaign#jsonSerialize`](githu) which are nested fields: the `coverImage` which is a linked asset entry, and the `type` field which computes based on a field in the `campaignSettings` field -- a linked entry.

Within the `getEntriesAsJson` function we can inspect the constructed `TruncatedCampaign` to see that those fields are plain `Link` objects, since Contentful won't implicitely fetch nested fields:
```
0 => TruncatedCampaign {#7445 ▼
      #entry: Entry {#6879 ▼
        #fields: array:18 [▼
          "internalTitle" => array:1 [▶]
          "title" => array:1 [▶]
          "slug" => array:1 [▶]
          "legacyCampaignId" => array:1 [▶]
          "campaignSettings" => array:1 [▼
            "en-US" => Link {#6849 ▼
              -linkId: "2fV9zH6PS8coEUoMQom2I0"
              -linkType: "Entry"
            }
          ]
          "template" => array:1 [▶]
          "endDate" => array:1 [▶]
          "callToAction" => array:1 [▶]
          "coverImage" => array:1 [▼
            "en-US" => Link {#6854 ▼
              -linkId: "4k8rv5sN0kii0AoCawc6UQ"
              -linkType: "Asset"
            }
          ]
          "campaignLead" => array:1 [▶]
          "affiliateSponsors" => array:1 [▶]
          "affiliatePartners" => array:1 [▶]
          "affirmation" => array:1 [▶]
          "pages" => array:1 [▶]
          "quizzes" => array:1 [▶]
          "socialOverride" => array:1 [▶]
          "landingPage" => array:1 [▶]
          "additionalContent" => array:1 [▶]
        ]
        -localeCode: "en-US"
        #localeCodes: array:1 [▶]
        #client: Client {#319 ▶}
        #sys: SystemProperties {#6847 ▶}
      }
    }
 
```

But this does mean, that when we serialize the entries, and attempt to grab the `coverImage` and `campaignSettings`, Contentful will have to query for those fields under the hood, which, multiplied by -even the paginated- `36` would be quite a nice amount of additional queries!


Indeed, removing those two nested fields from the `TruncatedCampaign#jsonSerialize`, results in a beautifully short query time:
```
"Querying Contentful! "
Carbon @1547066202 {#377 ▼
  date: 2019-01-09 20:36:42.036173 UTC (+00:00)
}
"Querying Contentful Done! "
Carbon @1547066202 {#416 ▼
  date: 2019-01-09 20:36:42.656710 UTC (+00:00)
}
"Constructing Entries! "
Carbon @1547066202 {#416 ▼
  date: 2019-01-09 20:36:42.657245 UTC (+00:00)
}
"Constructing Entries Done! "
Carbon @1547066202 {#416 ▼
  date: 2019-01-09 20:36:42.671446 UTC (+00:00)
}
"Transforming to JSON! "
Carbon @1547066202 {#416 ▼
  date: 2019-01-09 20:36:42.671899 UTC (+00:00)
}
"Transforming to JSON Done! "
Carbon @1547066202 {#1126 ▼
  date: 2019-01-09 20:36:42.725756 UTC (+00:00)
}
```

An even 10 millisecond transformation!


So I guess the question is how we can shorten these insane nested field queries. Perhaps by bundling them (e.g. having them be returned in the top level query to begin with), or something of that nature.

**Comment by weerd** [comment]
🤔

**Comment by weerd** [comment]
Is there anything with the API that we can force it to grab `Link` objects at least 1 level deep or something?

**Comment by mendelB** [comment]
Yeah that's the strange thing though, altering the `setInclude` param doesn't seem to affect the result! It should cause it to resolve nested queries to n level, but it seems to return the same thing no matter the setting.
It's def in the documentation, so not sure why it's inaffective https://contentful.github.io/contentful.php/api/4.1.0/Contentful/Delivery/Query.html#method_setInclude

**Comment by weerd** [comment]
Does it mean it'll retrieve nested items, but technically not resolve them. It grabs nested `Link` items enough to _know_ it's ID, and other meta data, but not enough to grab the actual field values... at least that's what it seems like.

**Comment by mendelB** [comment]
The general API documentation says the `include` param specifies how many levels to resolve though, which I imagine should apply to the SDK too, right?
https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/links

**Comment by mendelB** [comment]
Or do you mean that's what they're referring to by 'resolve'?

**Comment by mendelB** [comment]
I replicated the SDKs query in Postman, and cross referenced that with a data dump of the result of the SDKs internal query before any building is done with the data, and they both *do* contain resolved links equivalent to the `setInclude` setting!

The top-level results are included in an `items` array, and the resolved links are in a `includes` array in the result JSON. Which checks out with the documentation:
> If the standard items array has not already retrieved the linked entries, they will be in the includes.Entry array. Linked assets are inside the includes.Asset array.

But once the SDK does some internal Entry building with the data, the result frustratingly, only ends up being only the top level `items` data constructed into Entries ☹️ 

I wasn't able to figure out concretely why the `includes` array is ignored. There definitely is a build function for it within the internal SDK builders, but it doesn't seem to ever get returned along with the items data. Gonna keep looking into it!

**Comment by mendelB** [comment]
The culprit seems to lie somewhere in the `Contentful\Delivery\Client#requestAndBuild` which returns the result of the `Contentful\Delivery\ResourceBuilder#build` method.

**Comment by mendelB** [comment]
I've dug into those builders (even on the updated SDK code) and it really doesn't seem like there's any access to the included resolved entries 😦 
I'm not really sure what to do beyond putting a question in the Contentful Community forum?

**Comment by mendelB** [comment]
The only reason I can think of as to what the value of the `include` array is if not being returned from the `getEntries` function - is that it is loaded in memory and would be grabbed locally when those fields are called, instead of making an additional query. 

Though the question would then be why there's such a massive delay when we indeed call for those fields in the `TruncatedCampaign` if they've already been eager loaded 🤔

**Comment by mendelB** [comment]
Do I feel like an absolute utter fool? Yeah.

The above theory is probably correct. It seems that the `includes` array is eager loaded to memory, and thus, the subsequent nested field queries are naturally much faster (grabbed from memory).

When I had the bright idea to actually test the query timing again with an `setInclude` of `1` - the query is beautifully quick:

```txt
"Querying Contentful! "
Carbon @1547226259 {#377 ▼
  date: 2019-01-11 17:04:19.430630 UTC (+00:00)
}
"Querying Contentful Done! "
Carbon @1547226260 {#3446 ▼
  date: 2019-01-11 17:04:20.928636 UTC (+00:00)
}
"Constructing Entries! "
Carbon @1547226260 {#3446 ▼
  date: 2019-01-11 17:04:20.929181 UTC (+00:00)
}
"Constructing Entries Done! "
Carbon @1547226260 {#3446 ▼
  date: 2019-01-11 17:04:20.936131 UTC (+00:00)
}
"Transforming to JSON! "
Carbon @1547226260 {#3446 ▼
  date: 2019-01-11 17:04:20.936610 UTC (+00:00)
}
"Transforming to JSON Done! "
Carbon @1547226261 {#3365 ▼
  date: 2019-01-11 17:04:21.027741 UTC (+00:00)
}
```

The issue seems to merely have been - that we *weren't* setting the `setInclude` to `1`, it's currently at `0`!

My error was that upon updating that setting, instead of retesting the timing, I was stuck at wondering why the return value of `getEntries` was still only showing the `Link`s and not the resolved `Link`'s entries. 🌴🤕 It's been a day. TGIF.

**Comment by mendelB** [comment]
How do we feel about a new `$include` param which defaults to `0` for the [`getEntriesAsJson`](https://github.com/DoSomething/phoenix-next/blob/master/app/Repositories/QueriesContentful.php#L21) method, which can be set to `1` from the call to `[getAllCampaignsPaginated](https://github.com/DoSomething/phoenix-next/blob/master/app/Http/Controllers/CampaignController.php#L33)` in the `CampaignController#index`?

**Comment by weerd** [comment]
> The issue seems to merely have been - that we weren't setting the setInclude to 1, it's currently at 0! https://github.com/DoSomething/phoenix-next/blob/master/app/Repositories/QueriesContentful.php#L25

OMG! I wish GH had 😱 as a possible reaction to a comment. Hot dang! Nice find!

**Comment by weerd** [comment]
> How do we feel about a new $include param which defaults to 0 for the getEntriesAsJson method, which can be set to 1 from the call to getAllCampaignsPaginated in the CampaignController#index?

Yeah, being able to control it seems like the right call. Although I wonder if we're now at 3 optional params that have defaults... maybe we switch to an `options` param that defaults to an empty array and toss `$limit`, `$skip`, and `$includeDepth` in there as array items. So we don't have to worry passing `null` to some of the params just to be able to pass `1` as the include depth.

**Comment by mendelB** [comment]
Ah that sounds smart! Alternatively, I was thinking we could add the `$include` param before the `$limit` and `$skip` params so that the `nulll`s can remain implicit -- or do you think it's better with `options` since it's quite a few optional params?

**Comment by weerd** [comment]
I think I prefer `options`. I was already not super keen with how you might have to pass `null` for `$limit` just to set a `$skip` value. I could also see us potentially adding more option items in the future. 🔮

**Comment by mendelB** [comment]
I see you borrowed Storm's crystal ball 😄 
Makes total sense -- will do!

**Comment by weerd** [comment]
🎉
