### ISSUE TITLE
SectionBlock for StoryPage

### ISSUE THREAD

**Issue by weerd** [DoSomething/phoenix-next#1267]
### User Story
As an admin on Contentful, I want to have the ability to create custom `SectionBlock`s within a `StoryPage` that will contain fields for all necessary content as well as customizable fields for background-colors and text-color.

#### Additional Information
_Any other info or references to cards/tickets from other services (Trello, etc)._
Pivotal ID: [#164144958](https://www.pivotaltracker.com/story/show/164144958)

### Why This Matters
This feature will allow customizing art-directed story pages to match the desired design for these experiences.

**Comment by weerd** [comment]
Since these `SectionBlock`s will have some design related customization options, we want to limit their use for the time being only on `StoryPage`s. Additionally, only admins will be able to create them.

@lkpttn do we want to limit editing them to Admins as well? or is only limiting creating them on story pages fine?

**Comment by weerd** [comment]
Currently, the expected structure for these `SectionBlock`s will include the following fields:

- internalTitle (string)
- title (string)
- subTitle (string)
- content (rich text)
- backgroundColor (string; regex limiting to `#xxxxxx`)
- textColor (string; regex limiting to `#xxxxxx`)

**Comment by DFurnes** [comment]
Do we need `title` and `subtitle`? I'd imagine those would just be headers in the content field.

**Comment by weerd** [comment]
Oh sorry, yeah. Got confused w/ the `title` and `subtitle` of the `StoryPage`. I'll remove.

**Comment by ngjo** [comment]
> @lkpttn do we want to limit editing them to Admins as well? or is only limiting creating them on story pages fine?

My two cents is that they should be able to edit -- would hate if there's say, a copy change, and they have to come to an admin to do it. We can provide some instructions on the limitations of what they can edit (i.e., limited editing experience and beyond text changes, you could break the page so reach out).

**Comment by weerd** [comment]
Closing this issue! We successfully launched the `StoryPage` and `SectionBlock` and all rejoiced! We shook hands 🤝  and high-fived ✋ in celebration of a job well done. 🎉
