### ISSUE TITLE
Deprecation warnings for PropTypes.

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/phoenix-next#170]
React moved PropTypes into an external package [in v15.5.0](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html). It's only a deprecation warning, but we should fix this up to reduce noise in the console.

**Comment by weerd** [comment]
Yeah, I read about this yesterday. Same with `createClass()` which we don't use, so we're safe there.

**Comment by DFurnes** [comment]
Fixed in #218.
