### ISSUE TITLE
Reportbacks are not being displayed on Sincerely Us.

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/phoenix-next#193]
_BUG_
-------------------
#### Current Behavior
The `api/v1/reportbacks` endpoint is not showing any reportbacks for [Sincerely Us], even though there _are_ reportbacks (at the moment, one promoted & one approved):

```
// https://www.dosomething.org/next/reportbacks?campaigns=7656&page=1

{
    "data": []
}
```

This is just a [straightforward proxy](https://github.com/DoSomething/phoenix-next/blob/3e3c5b9710576ca7d4e896a87b23eed4a30011e5/app/Services/PhoenixLegacy.php#L96-L112) to the [Phoenix reportback index](https://github.com/DoSomething/phoenix/blob/dev/documentation/endpoints/reportbacks.md#retrieve-all-reportbacks) that adds an `as_user` field so users can see their own reaction status for each item in the feed.

#### Desired Behavior
We should see any reportbacks that have been promoted or approved.

#### Steps to Replicate
This is happening consistently when hitting any of the above pages/endpoints.

#### Why This Matters
We want to be able to show reportback images on the feed for launch.

#### Countries Affected (optional)
All.

#### OS/Browser (optional)
Every damn one.

#### Relevant Screenshots + Links
- [Sincerely Us (next)](http://www.dosomething.org/us/campaigns/sincerely-us)
- [Sincerely Us (legacy)](https://www.dosomething.org/us/node/7656)
- [Reportback Admin](https://www.dosomething.org/us/node/7656/rb)

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🐛 Approved or Promoted RBs aren't showing up in the Feed on Production 🐛](https://trello.com/c/qKgX55EZ/534-approved-or-promoted-rbs-aren-t-showing-up-in-the-feed-on-production)

**Comment by deadlybutter** [comment]
FWIW - Also returning an empty array on Thor, confirmed there are 2 reportbacks it should be displaying

https://thor.dosomething.org/api/v1/reportbacks?campaigns=7656&count=1
https://thor.dosomething.org/us/node/7656/rb

**Comment by DFurnes** [comment]
This has been fixed by using the `/v1/reportback-items` endpoint instead in #197.
