### ISSUE TITLE
Scrollbars are displayed on the navigation component.

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/phoenix-next#196]
The `overflow-x` adds scrollbars (or awkward cropping) in some instances.

![screen shot 2017-04-14 at 2 32 16 pm](https://cloud.githubusercontent.com/assets/583202/25052322/40859f26-211f-11e7-8259-5b77fb9d8eb5.png)

**Comment by DFurnes** [comment]
References #180.

**Comment by deadlybutter** [comment]
lets put a media query around the overflow so it only shows up on small small screens

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Up and down scroll-wonk - weirdness of he scroll overflow w/ the tab navigation component](https://trello.com/c/iEQATRFA/542-up-and-down-scroll-wonk-weirdness-of-he-scroll-overflow-w-the-tab-navigation-component)
