### ISSUE TITLE
Users are being given the wrong session.

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/phoenix-next#207]
_BUG_
-------------------
#### Current Behavior
Currently, most (all?) of the users on Phoenix Next production are getting the session for [the same user](https://aurora.dosomething.org/users/5544d41e469c64ec7d8b48f9). This means we're all seeing her reportbacks, and reporting back on her behalf.

#### Desired Behavior
That shouldn't be happening.

#### Steps to Replicate
It seems like everyone who goes to [the campaign](https://www.dosomething.org/us/campaigns/sincerely-us/action) has this issue.

You can see which Northstar ID you have by dumping out the preloaded state in `window.STATE.user`:

<img width="374" alt="screen shot 2017-04-17 at 11 16 09 am" src="https://cloud.githubusercontent.com/assets/583202/25093224/458899a0-235f-11e7-998e-5c98a94666ac.png">

#### Why This Matters
We want users to be able to log in as _themselves_!

#### Countries Affected (optional)
…

#### OS/Browser (optional)
…

#### Relevant Screenshots + Links
- [Phoenix Next production](https://www.dosomething.org/us/campaigns/sincerely-us/action)
- [Patient 0's profile](https://aurora.dosomething.org/users/5544d41e469c64ec7d8b48f9)

**Comment by deadlybutter** [comment]
<img width="960" alt="screen shot 2017-04-17 at 11 17 36 am" src="https://cloud.githubusercontent.com/assets/897368/25093268/7eae6f2a-235f-11e7-9819-e29461a846a3.png">

Worked for me on login just now

**Comment by deadlybutter** [comment]
<img width="365" alt="screen shot 2017-04-17 at 11 18 28 am" src="https://cloud.githubusercontent.com/assets/897368/25093292/99175fa2-235f-11e7-8564-277907dd68cf.png">

**Comment by DFurnes** [comment]
Phoenix Next authenticates using [Gateway](https://github.com/DoSomething/gateway) and Laravel's built-in authentication & Redis session driver. We have seen some odd behavior with [mismatched state tokens](https://github.com/DoSomething/phoenix-next/issues/188) on this app, but otherwise this is all the exact same authentication flow we use on Aurora, Gladiator, Rogue, Voting App, and Celebs Gone Good (and the same Northstar endpoint as we use w/ Drupal module in Phoenix Ashes).

**Comment by DFurnes** [comment]
So far we've tried:
 - Checking the Redis session store – there are a bunch of normal looking `laravel:*` sessions in Redis. We're also using the same Redis database as we use for Drupal, which shouldn't be causing issues since keys are prefixed `ds:` or `laravel:` but is still strange.
 - Examining the Northstar token response: the correct user ID is returned in the access token on local,   and on production when we logged the payload in the auth code response.

…

**Comment by DFurnes** [comment]
Another piece in the puzzle! New users do seem to be getting entries in the Phoenix Next `users` table... we checked and a newly-logged in user has a Northstar ID there.

**Comment by DFurnes** [comment]
@deadlybutter has spun up a new Phoenix Next instance on Heroku that does not seem to be exhibiting these problems.

We're going to try updating the Fastly routing rules to 301 redirect users on `/us/campaigns/sincerely-us` to the new Heroku instance `https://phoenix-next.herokuapp.com/us/campaigns/sincerely-us/`. That way users can still signup and reportback while we still debug on a separate path.

**Comment by DFurnes** [comment]
@blisteringherb has updated the Fastly config to 301 redirect users to the [Heroku instance](https://phoenix-next.herokuapp.com/us/campaigns/sincerely-us/), which does not seem to have the same issue as we're seeing on our own infrastructure.

At the moment, all traffic to `/us/campaigns/sincerely-us/*` is being redirected to the same page on the Heroku end: which for now is the `.../pages/scholarship` path.

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🐛 🚨 (21) All session are Chloe at the moment 🚨 🐛](https://trello.com/c/v5d1KYTu/553-21-all-session-are-chloe-at-the-moment)

**Comment by DFurnes** [comment]
What we know so far:
- The problem (probably) can’t be in Phoenix, since those requests are all made as one `ds-api@dosomething.org` user with a `?as_user=<id>` in the request URL set by Next.
- It can’t be Northstar because we’ve logged out the access token & user ID in the Gateway auth code method & they’re the same thing we expect!
- We’ve grabbed the user’s session token (from the cookie in the browser) and run it through Laravel’s decrypter (via Artisan tinker). It contained the expected user’s ID even though the page was rendering as Chloe!
- New user logins or registrations do correctly add a record to the `users` SQL table, even though people “appear” to be registered or signed in as Chloe.
- The problem (probably) can’t be Fastly, because setting the IP in our `/etc/hosts` and connecting directly still shows the same issue (and we’ve verified that Fastly headers aren’t being applied when we do this, so it can’t be Fastly…?)

**Comment by DFurnes** [comment]
Update:

We've switched out the Redis server to be a instance specifically for Phoenix Next (since it was originally sharing a single database with Phoenix Ashes, and only differentiating keys by their `ds:` or `laravel:` prefix). This new `-n 1` database is still showing the same issue though. 😢

**Comment by DFurnes** [comment]
Our current theory is that there's a mixup somewhere between the user's browser (which has the correct session token) and the application server (which seems to always think the session is Chloe's).... maybe in HAProxy...? Nginx? 🤔

**Comment by DFurnes** [comment]
We've also talked through the differences between the AWS instance for next.dosomething.org (which is the first server to be provisioned using our new Ansible profile) and the other instances we've used previously (for Northstar and co.) and couldn't think of any obvious differences that would cause this issue.

**Comment by DFurnes** [comment]
Breakthrough! I think we're calling `User::find` somewhere, and it's searching with a Northstar ID (like `58f52ca2a0bfad67691d9753`), but the primary key on that model is set to the numeric `id` column in the database. PHP casts the string to an integer, and tries to find a user with `id` of `58`... which always loads the same person... Chloe.

<img width="962" alt="screen shot 2017-04-17 at 5 03 35 pm" src="https://cloud.githubusercontent.com/assets/583202/25104820/d13cf146-238f-11e7-9491-62cc1b0f59c6.png">

**Comment by DFurnes** [comment]
This has been fixed in Phoenix Next by #210, and I'll make a patch to Gateway in the future.

**Comment by mirie** [comment]
@DFurnes would you like @ngjo to make a card for this Gateway patch in Trello ?

**Comment by DFurnes** [comment]
@mirie Sure, that'd be great!

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a developer, I want to fix Gateway so that it's not trying to find a user with the ID of 58](https://trello.com/c/H9Wi8zb0/564-as-a-developer-i-want-to-fix-gateway-so-that-it-s-not-trying-to-find-a-user-with-the-id-of-58)

**Comment by DFurnes** [comment]
Closing, since this has been fixed! 🔨
