### ISSUE TITLE
Reportback Uploader Bug List

### ISSUE THREAD

**Issue by lkpttn** [DoSomething/phoenix-next#212]
### Error messages:

- Shouldn’t clear out whole submission field
- References “Why Participated” field - improper name

### Mobile photos:
![screen shot 2017-04-18 at 10 58 00 am](https://cloud.githubusercontent.com/assets/1865372/25137882/056465f2-2427-11e7-8e07-ff9bccf94064.png)
- Show original rotation, instead of metadata rotation (ask Shae)

### Large/tall photos: 
![screen shot 2017-04-18 at 10 39 58 am](https://cloud.githubusercontent.com/assets/1865372/25137820/da754d70-2426-11e7-9d46-8744ce94845c.png)
- Overflows the boundaries
- Upload your photo text remains
- Can’t reselect photos

### Action page gallery:
![screen shot 2017-04-18 at 10 40 49 am](https://cloud.githubusercontent.com/assets/1865372/25137968/3ceb24de-2427-11e7-9349-7776a895b2f9.png)
- Shows up at original aspect ratio in gallery until refresh
- Doesn’t show impact number
- Doesn’t show user name
- Doesn’t show reaction count

**Comment by weerd** [comment]
Moving this convo over from Slack:

> yeah, so that happens because I’m using the supplied image for the immediate showing in the gallery, since Drupal only returns an rb item ID in successful posting and nothing else. So I’d have to make another call to Phoenix to get the cropped version, which might seem what I will end up having to do until Rogue is ready ¯\_(ツ)_/¯

@lkpttn @ngjo

**Comment by weerd** [comment]
> Show original rotation, instead of metadata rotation (ask Shae)

We decided for the MVP to not deal w/ rotation and it has to get edited by the campaign leads when reviewing.

**Comment by weerd** [comment]
> Shouldn’t clear out whole submission field

see regarding the submission field clearing. https://github.com/DoSomething/phoenix-next/pull/200
It's a known thing and aiming to update soon 😄

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a developer, I want to go through Luke's Design QA doc and fix design issues. <should i break this up into other cards?>](https://trello.com/c/WLcUtDcL/551-as-a-developer-i-want-to-go-through-luke-s-design-qa-doc-and-fix-design-issues-should-i-break-this-up-into-other-cards)

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🐛 Fix the image spilling outside of the RB uploader 🐛](https://trello.com/c/N1AjB3uj/576-fix-the-image-spilling-outside-of-the-rb-uploader)
