### ISSUE TITLE
Update profile avatar image on Github

### ISSUE THREAD

**Issue by weerd** [DoSomething/phoenix-next#231]
![image](https://cloud.githubusercontent.com/assets/105849/25501486/eff56d56-2b60-11e7-94ef-07478f503676.png)

As a developer on Github, I would prefer to see the tonguecat avatar for @ngjo profile image 💃 

:trollface:

**Comment by ngjo** [comment]
ASK AND YOU SHALL RECEIVE 

meow

**Comment by weerd** [comment]
Yaiiiis! 👍 🏆 👅 🐈 🎉 💃

**Comment by DFurnes** [comment]
I'm so happy about this. 👅 👏
