### ISSUE TITLE
Competitions Prompt not rendering on iOS mobile web

### ISSUE THREAD

**Issue by lkpttn** [DoSomething/phoenix-next#248]
# MAJOR BUG
On iOS mobile web (Safari and Chrome) the competition prompt is not rendering correctly and users can't read/join competitions. Not able to replicate on Android devices or desktop browsers with small windows. The title should also read "Go Above and Beyond", maybe indicative of a botched deploy?

**Desired Behavior**
The block should render appropriately and allow users to join competitions. Should display appropriate post-joining copy.

![screen shot 2017-05-09 at 4 23 29 pm](https://cloud.githubusercontent.com/assets/1865372/25870950/e59bae16-34d3-11e7-996f-db6498a67550.png)

**Steps to Replicate**
1 - Load the campaign on an iOS device
2- Join the campaign and move to the action tab
3 - The competitions prompt will not display correctly.

![image uploaded from ios](https://cloud.githubusercontent.com/assets/1865372/25870711/10f8daee-34d3-11e7-8c8e-eaf05b2186d7.jpg)

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UNPLANNED WORK: 🐛 Competition block isn't showing up on mobile 🐛](https://trello.com/c/Q7DzyS8E/632-unplanned-work-competition-block-isn-t-showing-up-on-mobile)
