### ISSUE TITLE
Competition mobile signup needs to scroll back up to success message

### ISSUE THREAD

**Issue by weerd** [DoSomething/phoenix-next#253]
On mobile, the competition block is longer due to the narrow viewport. When clicking on the button on the bottom of the block to "join competition", after a successful signup it seems like nothing happened because the success message is much smaller than the original window, so it seems to just disappear. One fix could be to scroll/move up to the top of the competition block via a page anchor link ⚓️  so the user can actually see the success message.

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a developer, I want to handle the post-opt in competition block better for mobile users](https://trello.com/c/feN7NLom/649-as-a-developer-i-want-to-handle-the-post-opt-in-competition-block-better-for-mobile-users)

**Comment by weerd** [comment]
Closing for now. If still an issue we can re-assess.
