### ISSUE TITLE
Campaign id is being potentially duplicated in the signups array

### ISSUE THREAD

**Issue by itsjoekent** [DoSomething/phoenix-next#272]
Noticed this in one of the Keen events. Doesn't seem super high priority but good to note down
```
    "data": [
      "7",
      "7"
    ],
```

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Campaign id is being potentially duplicated in the signups array](https://trello.com/c/5YMEcywW/666-campaign-id-is-being-potentially-duplicated-in-the-signups-array)
