### ISSUE TITLE
Fix notification z-index

### ISSUE THREAD

**Issue by deadlybutter** [DoSomething/phoenix-next#323]
<img width="353" alt="screen shot 2017-06-28 at 1 50 17 pm" src="https://user-images.githubusercontent.com/897368/27652157-c30eddd0-5c08-11e7-9d11-341700d31cf4.png">

**Comment by weerd** [comment]
The z-indexes are now specified in the toolbox SCSS file, so just add a new variable in there so we can keep track 💃
