### ISSUE TITLE
Fix review apps

### ISSUE THREAD

**Issue by deadlybutter** [DoSomething/phoenix-next#33]

**Comment by deadlybutter** [comment]
Setup script did run, 

```
2017-02-10T15:31:04.661479+00:00 app[api]: Starting process with command `(sh bootstrap/setup.sh); echo "1dfe76113a7ead5edacd1d0257337580 $?"` by user machines@dosomething.org
```

In the test branch I deployed, I also removed the `npm install -only dev` step & added a config variable (`NPM_CONFIG_PRODUCTION=false`) which I confirmed is in the review build. 

Looking at the dyno, seems like they installed properly.

![screen shot 2017-02-10 at 10 37 49 am](https://cloud.githubusercontent.com/assets/897368/22832686/06599466-ef7d-11e6-9e03-b28e8b257a6e.png)

**Comment by deadlybutter** [comment]
The command itself runs fine, and even notices all of the new scss files

![screen shot 2017-02-10 at 10 39 04 am](https://cloud.githubusercontent.com/assets/897368/22832733/3ae45482-ef7d-11e6-8ca2-eedcad5d2ff0.png)

My guess is it loses file system permissions in the post-deploy step, I can hack around this though (I think, one sec)

**Comment by deadlybutter** [comment]
So I can be 100% sure its running webpack post install, 

```
-----> Building dependencies
       Installing node modules (package.json)
       
       > undefined postinstall /tmp/build_56589a1e5ce854e522dba017f3136eb5/DoSomething-phoenix-next-1d1b6d8
       > npm run clean && npm run modernizr && NODE_ENV=production webpack
       
       
       > @ clean /tmp/build_56589a1e5ce854e522dba017f3136eb5/DoSomething-phoenix-next-1d1b6d8
       > rm -rf public/dist
       
       
       > @ modernizr /tmp/build_56589a1e5ce854e522dba017f3136eb5/DoSomething-phoenix-next-1d1b6d8
       > modernizr -c node_modules/@dosomething/forge/modernizr.json -d public/dist/modernizr.js
       
       Modernizr build saved to public/dist/modernizr.js
       Hash: 31ffa0c396761adb6576
       Version: webpack 1.14.0
       Time: 2747ms
       Asset       Size  Chunks             Chunk Names
       12f9aba58b7bb2668f011f5c9aa5b4fe.png    92.1 kB          [emitted]
       app.js  630 bytes       0  [emitted]  app
       app.css    9.33 kB       0  [emitted]  app
       + 11 hidden modules
       Child extract-text-webpack-plugin:
       + 4 hidden modules
       Child extract-text-webpack-plugin:
       + 2 hidden modules
       Child extract-text-webpack-plugin:
       + 2 hidden modules
       Child extract-text-webpack-plugin:
       + 2 hidden modules
       Child extract-text-webpack-plugin:
       + 2 hidden modules
       Child extract-text-webpack-plugin:
       + 2 hidden modules
       Child extract-text-webpack-plugin:
       + 2 hidden modules
```

but still nothing updating. I've run webpack on `postinstall` in Node projects before, so I don't think that's the issue.

**Comment by deadlybutter** [comment]
So I'm starting to think my app.json changes aren't reflected, it's basing everything off of the main branch, I think

**Comment by deadlybutter** [comment]
Well shit, this might have something to do with it

![screen shot 2017-02-13 at 1 24 21 pm](https://cloud.githubusercontent.com/assets/897368/22896910/cad2486e-f1ef-11e6-8506-9fda69f24497.png)

**Comment by deadlybutter** [comment]
Yeah, looks like it's trying to load these two over HTTP, but Heroku is on HTTPS 

http://phoenix-next-pr-34.herokuapp.com/dist/app.js

**Comment by weerd** [comment]
hmmm, don't know the full context but is there a way to try that `//:something.com` trick and let Heroku decide whether the protocol to use is secure or not? Just a random thought 🤔

**Comment by deadlybutter** [comment]
@weerd We're using this `asset(...)` function to wrap `dist/app.js` and I'm not sure I understand the point. Also according to the Laravel docs its supposed to handle HTTP/HTTPS https://laravel.com/docs/5.4/helpers#method-asset

**Comment by deadlybutter** [comment]
Yeah removing `asset(...)` fixed it, I just kept the `/dist/app.js` string

heres the review app with it working http://phoenix-next-pr-32.herokuapp.com/

**Comment by DFurnes** [comment]
@deadlybutter This isn't a robust fix, since any other links generated with the Laravel's URL generator will also be pointed at insecure `http://` URLs. Take a look at [this documentation](https://devcenter.heroku.com/articles/getting-started-with-laravel#trusting-the-load-balancer) for a better fix.

**Comment by deadlybutter** [comment]
Fixed in https://github.com/DoSomething/phoenix-next/pull/35
