### ISSUE TITLE
`Embed` links with flex on mid-size screens visual bug

### ISSUE THREAD

**Issue by mendelB** [DoSomething/phoenix-next#674]
### Current Behavior
What is the current behavior?
On mid-size screens, embedded links rendered with the [`Embed`](https://github.com/DoSomething/phoenix-next/blob/dev/resources/assets/components/Embed/index.js) component that occupy less than the full width of the page (e.g `--two-thirds` with flex) start to stretch vertically to accommodate having the link text appear on the right of the link image.
![image](https://user-images.githubusercontent.com/12417657/35984778-22cfd830-0cc3-11e8-9f11-cdf5ddc0a718.png)

### Expected Behavior
Describe the behavior you are expecting.
We'd expect the card to perhaps pop over to the setting for smaller screens, where the link image pops above the description, allowing the description more breathing room and taking up the full width of the page.
![image](https://user-images.githubusercontent.com/12417657/35985041-b1bae3e6-0cc3-11e8-9ae6-2a795bbee9c9.png)

#### Additional Information
https://github.com/DoSomething/phoenix-next/pull/673#issuecomment-364165323

**Comment by lkpttn** [comment]
In general I'm not happy with how these images are coming out. It might be worth looking at constraining the image container size and just having the image cover that.

**Comment by mendelB** [comment]
Fixed with #889
