### ISSUE TITLE
Photo Reportback Uploading on `phoenix-preview` bug

### ISSUE THREAD

**Issue by mendelB** [DoSomething/phoenix-next#681]
### Current Behavior
What is the current behavior?

**1.**
> On Thor, an error is being thrown when this photo is being uploaded. Prod, its fine. I think its because of Heroku.

![image1](https://user-images.githubusercontent.com/12417657/36048516-7ead339c-0dad-11e8-8a5b-877cfa342bd0.JPG)

**2:**
Reporting back with the photo uploader seems to randomly return a `500` error with the following json response:
```json
{"error":{"code":500,"message":"Looks like something went wrong. We've noted the problem and will try to get it fixed!"}}
```

I grabbed some logs from Heroku:
<img width="1192" alt="screen shot 2018-02-09 at 12 11 54 pm" src="https://user-images.githubusercontent.com/12417657/36048632-d986d2a0-0dad-11e8-849a-0a6f8d5d4970.png">
[ds-phoenix-staging-logs-1518208119644.txt](https://github.com/DoSomething/phoenix-next/files/1712351/ds-phoenix-staging-logs-1518208119644.txt)

The above would happen with images of a smaller size, otherwise, I'd generally bump into the `500` error.

### Expected Behavior
Describe the behavior you are expecting.
Both cases **do not** occur on prod. This seems to be a Heroku or thor/staging specific problem.

#### Additional Information
_Any other info or references to cards/tickets from other services (Trello, etc)._
Pivotal ID: [#155037862](https://www.pivotaltracker.com/story/show/155037862)

### Steps to Reproduce
Please provide detailed steps for reproducing the issue.
Go through the regular reportback flow with either the image attached above or some smaller file. 

[Here's a fun example](https://user-images.githubusercontent.com/12417657/36052148-7703178a-0dba-11e8-865a-cd3539a5906a.jpg)

**Comment by weerd** [comment]
One thing I found is that our [`Procfile`](https://github.com/DoSomething/phoenix-next/blob/a41b1e826ac1dfd458a06a5fa9b16e25fc93f8b4/Procfile) for Heroku defines the use of Apache instead of Nginx. So I'll be making a PR to update that. It _may_ be that some of the settings we adjusted for uploads weren't taking effect if they were defined for Nginx, but we were building the app with Apache. I haven't dug further on this, but it's a suspicion.... 🤔

**Comment by DFurnes** [comment]
It doesn't look like we ever overrode any settings here, so we're probably limited to 2MB. Oy.

For reference, here's Rogue's [`Profile`](https://github.com/DoSomething/rogue/blob/c7743e313d616fbde7cd4c2bf1adf876618c7421/Procfile), [`nginx.conf`](https://github.com/DoSomething/rogue/blob/c7743e313d616fbde7cd4c2bf1adf876618c7421/nginx.conf), and [`.user.ini`](https://github.com/DoSomething/rogue/blob/master/public/.user.ini).

**Comment by weerd** [comment]
So my suspicion was right! Huzzah! At least it's something we know how to fix 💃  I'll make an update PR soon and we can fix this up! Thanks for further 🕵️  @DFurnes 

cc: @ashleybaldwin

**Comment by weerd** [comment]
Edits to Heroku either did not seem to take properly. Re-opening for now.

**Comment by weerd** [comment]
![image](https://user-images.githubusercontent.com/105849/36280137-53f0e9b4-1267-11e8-914a-7b85324d1404.png)

Fixed! Huxley is forever accepted as a suitable Reportback 🎉
