### ISSUE TITLE
Make the "legacy campaign ID" field unique.

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/phoenix-next#685]
### Current Behavior
When the "Legacy Campaign ID" field is not unique, things can break! For example, [Runscope tests](https://www.runscope.com/radar/4ufmq5rbj5yx/38eb227a-c1a1-432d-8be8-5b11817c4071/overview).

### Expected Behavior
We should not allow people (like me) to break things! This field should have a "unique" validation rule, just like the slug field does.

#### Additional Information
N/A

### Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Create a campaign with the same legacy ID as another.
2. Things break, but the Contentful UI doesn't tell you they will!

## Context
N/A

### Relevant Screenshots + Links
N/A

**Comment by weerd** [comment]
Completed on Contentful. Cleaning out test campaigns.
