### ISSUE TITLE
Error when loading `/campaigns` page.

### ISSUE THREAD

**Issue by weerd** [DoSomething/phoenix-next#93]
![image](https://cloud.githubusercontent.com/assets/105849/24253793/9ef96caa-0fb7-11e7-807a-60c77813d2fb.png)

App is trying to set preloaded state for RBs when on the `/campaigns` index page and it shouldn't be loading RBs there.

**Comment by ngjo** [comment]
@weerd I don't think this is happening anymore! I just went to /campaigns from PN and it loaded fine logged in and out. Can we close?

**Comment by weerd** [comment]
![image](https://user-images.githubusercontent.com/105849/27607003-744a0b6a-5b50-11e7-88e0-abb12ae7080a.png)

I'm still seeing an error on Thor 🙃

**Comment by weerd** [comment]
Likely fixed by #763
